repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.4.0
    hooks:
    -   id: flake8
        exclude: ^docs/.*$
-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: pytest --cov
        language: system
        types: [python]
        pass_filenames: false
